apiVersion: apps/v1
kind: Deployment

metadata:
  name: hello-node

spec:
  replicas: 5

  selector:
    matchLabels:
      app: hello-node

  template:
    metadata:
      labels:
        app: hello-node

    spec:
      containers:
        - name: hello-node
          image: surajsdm/hello-node:43
          imagePullPolicy: Always

          ports:
            - containerPort: 3000

          env:
            - name: APP_VERSION
              value: "38"

            - name: BUILD_NUMBER
              value: "38"

            - name: GIT_COMMIT
              value: "abcdefg"