apiVersion: apps/v1
kind: Deployment

metadata:
  name: hello-node

spec:
  replicas: 5

  selector:
    matchLabels:
      app: hello-node

  template:
    metadata:
      labels:
        app: hello-node

    spec:
      containers:
        - name: hello-node
          image: surajsdm/hello-node:49
          imagePullPolicy: Always

          ports:
            - containerPort: 3000

          env:
            - name: APP_VERSION
              value: "49"

            - name: BUILD_NUMBER
              value: "49"

            - name: GIT_COMMIT
              value: "C:\Users\super\.jenkins\workspace\hello-node-ci>git rev-parse --short=7 HEAD 
8152b52"
